module.exports = {
    config: {
        opacity: 0.85,
        updateChannel: 'stable',
        fontSize: 14,
        fontFamily: "FiraCode Nerd Font",
        lineHeight: 1,
        letterSpacing: 0,
        cursorColor: 'rgba(248,28,229,0.8)',
        cursorAccentColor: '#011627',
        cursorShape: 'BLOCK',
        cursorBlink: false,
        foregroundColor: '#fff',
        backgroundColor: '#011627',
        selectionColor: 'rgba(248,28,229,0.3)',
        borderColor: '#011627',
        colors: {
            black: '#000000',
            red: '#C51E14',
            green: '#1DC121',
            yellow: '#FFFA72',
            blue: '#0A2FC4',
            magenta: '#C839C5',
            cyan: '#20C5C6',
            white: '#C7C7C7',
            lightBlack: '#686868',
            lightRed: '#FD6F6B',
            lightGreen: '#67F86F',
            lightYellow: '#EA05EA',
            lightBlue: '#6A76FB',
            lightMagenta: '#FD7CFC',
            lightCyan: '#68FDFE',
            lightWhite: '#FFFFFF',
            limeGreen: '#32CD32',
            lightCoral: '#F08080',
        },
        shell: 'pwsh.exe',
    },
    plugins: ["hyperpower", "hyper-opacity", "hyperminimal"],
};